- name: Install Base Packages
  ansible.builtin.apt:
    pkg:
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https

- name: Install Caddy GPG
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Install Caddy List
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list

- name: Install Caddy Package
  ansible.builtin.apt:
    name: caddy
    update_cache: true
