- name: Disable Password Authentication Over SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication no

- name: Run ssh-keygen -A
  shell: ssh-keygen -A

- name: Restart SSH
  shell: service ssh restart
