- name: PHP FPM Configuration error_reporting = E_ALL
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '^error_reporting = '
    line: error_reporting = E_ALL

- name: PHP FPM Configuration display_errors = Off
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '^display_errors = '
    line: display_errors = Off

- name: PHP FPM Configuration cgi.fix_pathinfo=0
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '^cgi.fix_pathinfo='
    insertafter: '^;cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0

- name: PHP FPM Configuration memory_limit = 512M
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '^memory_limit = '
    line: memory_limit = 512M

- name: PHP FPM Configuration date.timezone = UTC
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '^date.timezone='
    insertafter: '^;date.timezone'
    line: date.timezone = UTC
