- name: check if swap file exists
  stat:
    path: "/swapfile"
  register: swap_file_check

- name: create swap file
  command: fallocate -l 1G /swapfile
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  file:
    path: "/swapfile"
    mode: 0600
  when: not swap_file_check.stat.exists

- name: format swap file
  command: mkswap /swapfile
  when: not swap_file_check.stat.exists

- name: turn on swap
  command: swapon /swapfile
  when: not swap_file_check.stat.exists

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "/swapfile"
    line: "/swapfile none swap sw 0 0"
  when: not swap_file_check.stat.exists

- name: set swapiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '30'
  when: not swap_file_check.stat.exists

- name: set vfs_cache_pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
  when: not swap_file_check.stat.exists
